### ISSUE TITLE
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421. ... from: command not found

### ISSUE THREAD

**Issue by slrslr** [Abu3safeer/subscene-user-subtitle-downloader#1]
On Debian 11 oldstable with Python 3.9.2

git clone https://github.com/Abu3safeer/subscene-user-subtitle-downloader.git
cd subscene-user-subtitle-downloader && chmod +x main.py
pip install -r requirements.txt
 ./main.py # or ./main.py https://subscene.com/u/1322169/subtitles
```
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
./main.py: line 2: from: command not found
./main.py: line 3: from: command not found
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
./main.py: line 5: from: command not found
./main.py: line 9: syntax error near unexpected token `('
./main.py: line 9: `url = input("Pleas type the profile link where you want me to start:\r\n")'
```

the error is shown after i hold mouse button, move, release mouse button or when i just mouse right click (the mouse cursor is changed to a cross instead of a writing symbol |)

**Comment by Abu3safeer** [comment]
I don't use debian, but from what I see it is from your system, not from the script.
You can try adding the environment to main.py 

edit main.py and add this line at the start 
```
#!/usr/bin/env python3
```

**Comment by slrslr** [comment]
That helped. Thank you.
```
$ ./main.py
Pleas type the profile link where you want me to start:
https://subscene.com/u/1322169/subtitles
Start Processing link https://subscene.com/u/1322169/subtitles
No subtitles. Press any key to exit...
```

Can "No subtitles" be related to Cloudflare captcha? (because i have once seen it on that page and accessing it using via CLI curl, I can see:

```
$ curl -I https://subscene.com/u/1322169/subtitles
HTTP/2 403 
date: Sat, 10 Feb 2024 ... GMT
content-type: text/html; charset=UTF-8
content-length: 15317
accept-ch: Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA
cross-origin-embedder-policy: require-corp
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-origin
origin-agent-cluster: ?1
permissions-policy: accelerometer=(),autoplay=(),browsing-topics=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
referrer-policy: same-origin
x-frame-options: SAMEORIGIN
cf-mitigated: challenge
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=..."}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
...
```

is there any workaround, maybe using proxy, but i do not know how, yet i can set SOCKS5 to diffrent IP if there is no other way (like enabling verbose mode for the script, using other download utility, User_Agent)?

**Comment by Abu3safeer** [comment]
I didn't update this project for two main reasons:

1. subscene is changing their security settings from time to time to prevent scraping.
2. The limit is 20 pages, that means old subtitle won't be fetched, it is not really useful tool since it is very limited.

Plus There are several subscene mirror sites that offer almost every subtitle uploaded here, so scraping those mirrors is better then subscene, and if you dig deeper you might find dumbs of the subscene database so you don't need any scraping at all.

**Comment by Abu3safeer** [comment]
Anyway if you want to use this tool with proxy, you can edit every line with ```requests.get``` , just add the proxy there and you are done, not special knowledge is needed.

**Comment by slrslr** [comment]
Thank you, I have tried to apply the proxy, but it still output "No subtitles."
```
proxy_ip = '127.0.0.1'
proxy_port = '1080'
proxy_url = f'socks5://{proxy_ip}:{proxy_port}'

#    file_download_page = requests.get(subtitle.get('link')).text
    file_download_page = requests.get(subtitle.get('link'), proxies={'http': proxy_url, 'https': proxy_url}).text

```
So I guess i have to resign using this script.
